# To get started with Dependabot version updates, you'll need to specify which
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/Dependabot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # KEINE groups, KEINE komplexen Einstellungen
    target-branch: "main"
